[package]
name = "rengodango"
version = "0.1.0"
edition = "2024"
authors = ["Wingscape"]

[dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[dependencies.serenity]
version = "0.12"
default-features = false
features = ["client", "gateway", "model", "rustls_backend"]
